### ISSUE TITLE
App is asleep. Wake it up!

### ISSUE THREAD

**Issue by snappbandit** [MainakRepositor/EV-Price#2]
App is booting!...

It is stuck there
![image](https://user-images.githubusercontent.com/78193289/236550608-da4cca4f-0cc9-485f-80aa-c178f9dcb406.png)

**Comment by MainakRepositor** [comment]
Thank you @snappbandit . The issue was due to the package called "atlair v.4". It has been updated.
I appreciate your reporting. Hope it works now.
